# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.5.1

jobs:
  build-and-test-uat:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: Declare domain blockchain
          command: echo 127.0.0.1 blockchain | sudo tee -a /etc/hosts
      - run:
          name: Declare domain wallet
          command: echo 127.0.0.1 wallet | sudo tee -a /etc/hosts
      - node/install-packages
      - run:
          name: Launch docker
          command: docker-compose up --build --detach --force-recreate
      - run:
          name: Run tests
          command: npm test
  build-and-test-playwright:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build wallet
          command: npm run build
      - run:
          name: Run tests
          command: npm run test:playwright
workflows:
  sample:
    jobs:
      - build-and-test-uat
      - build-and-test-playwright
